package com.example.bff.health.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.lang.Nullable;

import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

/**
 * Cached allergy records from ECDH API.
 * Uses MongoDB TTL index for automatic expiration.
 */
@Document(collection = "allergies")
public record AllergyEntity(
        @Id String id,
        @Indexed String memberEid,
        List<AllergyRecord> records,
        Instant fetchedAt,
        @Indexed(name = "expiresAt_ttl", expireAfterSeconds = 0) Instant expiresAt,
        @Nullable List<Float> embeddings  // Future: AI search embeddings
) {
    /**
     * Individual allergy record.
     */
    public record AllergyRecord(
            String id,
            String allergenCode,
            String allergenName,
            String category,       // food, medication, environment
            String severity,       // mild, moderate, severe
            String reaction,
            LocalDate onsetDate,
            String status          // active, inactive, resolved
    ) {}

    /**
     * Create a new entity with calculated expiration.
     */
    public static AllergyEntity create(
            String memberEid,
            List<AllergyRecord> records,
            Duration ttl
    ) {
        Instant now = Instant.now();
        return new AllergyEntity(
                null,  // ID generated by MongoDB
                memberEid,
                records,
                now,
                now.plus(ttl),
                null   // No embeddings initially
        );
    }

    /**
     * Check if this cached entity has expired.
     */
    public boolean isExpired() {
        return expiresAt != null && Instant.now().isAfter(expiresAt);
    }

    /**
     * Get the number of records.
     */
    public int recordCount() {
        return records != null ? records.size() : 0;
    }
}
