package com.example.bff.health.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.lang.Nullable;

import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

/**
 * Cached health condition records from ECDH API.
 * Uses MongoDB TTL index for automatic expiration.
 */
@Document(collection = "conditions")
public record ConditionEntity(
        @Id String id,
        @Indexed String memberEid,
        List<ConditionRecord> records,
        Instant fetchedAt,
        @Indexed(name = "expiresAt_ttl", expireAfterSeconds = 0) Instant expiresAt,
        @Nullable List<Float> embeddings  // Future: AI search embeddings
) {
    /**
     * Individual health condition record.
     */
    public record ConditionRecord(
            String id,
            String conditionCode,      // ICD-10 or SNOMED code
            String conditionName,
            String category,           // chronic, acute, etc.
            LocalDate onsetDate,
            @Nullable LocalDate abatementDate,  // null if ongoing
            String clinicalStatus,     // active, recurrence, inactive
            String verificationStatus  // confirmed, provisional, differential
    ) {}

    /**
     * Create a new entity with calculated expiration.
     */
    public static ConditionEntity create(
            String memberEid,
            List<ConditionRecord> records,
            Duration ttl
    ) {
        Instant now = Instant.now();
        return new ConditionEntity(
                null,  // ID generated by MongoDB
                memberEid,
                records,
                now,
                now.plus(ttl),
                null   // No embeddings initially
        );
    }

    /**
     * Check if this cached entity has expired.
     */
    public boolean isExpired() {
        return expiresAt != null && Instant.now().isAfter(expiresAt);
    }

    /**
     * Get the number of records.
     */
    public int recordCount() {
        return records != null ? records.size() : 0;
    }
}
