package com.example.bff.health.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.lang.Nullable;

import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

/**
 * Cached immunization records from ECDH API.
 * Uses MongoDB TTL index for automatic expiration.
 */
@Document(collection = "immunizations")
public record ImmunizationEntity(
        @Id String id,
        @Indexed String memberEid,
        List<ImmunizationRecord> records,
        Instant fetchedAt,
        @Indexed(name = "expiresAt_ttl", expireAfterSeconds = 0) Instant expiresAt,
        @Nullable List<Float> embeddings  // Future: AI search embeddings
) {
    /**
     * Individual immunization record.
     */
    public record ImmunizationRecord(
            String id,
            String vaccineCode,
            String vaccineName,
            LocalDate administrationDate,
            String provider,
            String lotNumber,
            String site,
            String status
    ) {}

    /**
     * Create a new entity with calculated expiration.
     */
    public static ImmunizationEntity create(
            String memberEid,
            List<ImmunizationRecord> records,
            Duration ttl
    ) {
        Instant now = Instant.now();
        return new ImmunizationEntity(
                null,  // ID generated by MongoDB
                memberEid,
                records,
                now,
                now.plus(ttl),
                null   // No embeddings initially
        );
    }

    /**
     * Check if this cached entity has expired.
     */
    public boolean isExpired() {
        return expiresAt != null && Instant.now().isAfter(expiresAt);
    }

    /**
     * Get the number of records.
     */
    public int recordCount() {
        return records != null ? records.size() : 0;
    }
}
