/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSummaryRouteImport } from './routes/app/summary'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppHealthSummaryRouteImport } from './routes/app/health-summary'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryRoute = AppSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthSummaryRoute = AppHealthSummaryRouteImport.update({
  id: '/health-summary',
  path: '/health-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/health-summary': typeof AppHealthSummaryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/summary': typeof AppSummaryRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/health-summary': typeof AppHealthSummaryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/summary': typeof AppSummaryRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/health-summary': typeof AppHealthSummaryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/summary': typeof AppSummaryRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/health-summary'
    | '/app/profile'
    | '/app/summary'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dashboard'
    | '/app/health-summary'
    | '/app/profile'
    | '/app/summary'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/health-summary'
    | '/app/profile'
    | '/app/summary'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/summary': {
      id: '/app/summary'
      path: '/summary'
      fullPath: '/app/summary'
      preLoaderRoute: typeof AppSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health-summary': {
      id: '/app/health-summary'
      path: '/health-summary'
      fullPath: '/app/health-summary'
      preLoaderRoute: typeof AppHealthSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHealthSummaryRoute: typeof AppHealthSummaryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSummaryRoute: typeof AppSummaryRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHealthSummaryRoute: AppHealthSummaryRoute,
  AppProfileRoute: AppProfileRoute,
  AppSummaryRoute: AppSummaryRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
