package com.example.bff.document.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * Document entity stored in MongoDB.
 * Documents always belong to a youth (member) - others act as delegates.
 */
@Document(collection = "documents")
public record DocumentEntity(
        @Id String id,
        @Indexed String memberId,  // Youth who owns the document (always the youth's ID)
        String fileName,           // Sanitized filename stored in S3
        String originalFileName,   // Original filename from upload
        String contentType,        // MIME type
        long fileSize,             // File size in bytes
        String s3Key,              // S3 object key
        String description,        // Optional description
        DocumentType documentType, // Category of document
        String uploadedBy,         // userId who uploaded (youth, parent, agent, etc.)
        String uploadedByPersona,  // Persona of the uploader
        Instant createdAt,
        Instant updatedAt
) {
    /**
     * Document type/category.
     */
    public enum DocumentType {
        IDENTIFICATION,   // ID cards, passports, birth certificates
        MEDICAL,          // Lab reports, prescriptions, medical records
        LEGAL,            // Court orders, custody documents
        CORRESPONDENCE,   // Letters, notices
        EDUCATION,        // Marksheets, certificates, school records
        OTHER
    }

    /**
     * Create a new document entity for upload.
     */
    public static DocumentEntity create(
            String memberId,
            String fileName,
            String originalFileName,
            String contentType,
            long fileSize,
            String s3Key,
            String description,
            DocumentType documentType,
            String uploadedBy,
            String uploadedByPersona
    ) {
        Instant now = Instant.now();
        return new DocumentEntity(
                null,  // ID generated by MongoDB
                memberId,
                fileName,
                originalFileName,
                contentType,
                fileSize,
                s3Key,
                description,
                documentType != null ? documentType : DocumentType.OTHER,
                uploadedBy,
                uploadedByPersona,
                now,
                now
        );
    }

    /**
     * Create a copy with updated timestamp.
     */
    public DocumentEntity withUpdatedAt(Instant updatedAt) {
        return new DocumentEntity(
                id, memberId, fileName, originalFileName, contentType,
                fileSize, s3Key, description, documentType,
                uploadedBy, uploadedByPersona, createdAt, updatedAt
        );
    }
}
